// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/categories": {
            "get": {
                "description": "Mengambil semua data kategori barang yang tersedia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Daftar Kategori",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Category"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/expenditure": {
            "get": {
                "tags": [
                    "Reports"
                ],
                "summary": "Laporan Pengeluaran (Filter)",
                "responses": {}
            },
            "post": {
                "tags": [
                    "Transactions"
                ],
                "summary": "Input Pengeluaran (Barang/Operasional)",
                "responses": {}
            }
        },
        "/api/products": {
            "get": {
                "description": "Mengambil data produk, bisa difilter berdasarkan nama atau kode barang",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Daftar Produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cari berdasarkan Nama atau Kode Barang",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ProductResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/receipt": {
            "get": {
                "tags": [
                    "Receipt"
                ],
                "summary": "Data Nota Shift",
                "responses": {}
            }
        },
        "/api/sales": {
            "get": {
                "description": "Mengambil data transaksi penjualan yang dikelompokkan berdasarkan nomor nota (invoice).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Laporan Penjualan (Dikelompokkan Per-Nota)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tanggal Mulai (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Akhir (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter Nama Member",
                        "name": "member",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter Metode Pembayaran",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SalesTransactionGroup"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Membuat transaksi penjualan per-nota. Untuk transaksi DP, status DP dan customer dicatat per-nota.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Input Penjualan Kasir (Per Nota / Invoice)",
                "parameters": [
                    {
                        "description": "Payload Penjualan Per-Nota",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.SalesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/sales/update-shift": {
            "put": {
                "tags": [
                    "Sales"
                ],
                "summary": "Update shift transaksi",
                "responses": {}
            }
        },
        "/api/sales/user/{user_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Laporan Penjualan User (Dikelompokkan Per-Nota)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SalesTransactionGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/sales/{id}": {
            "put": {
                "description": "Melunasi transaksi penjualan berstatus DP untuk satu nota secara utuh.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Pelunasan Transaksi Penjualan (Per-Nota)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sales ID atau Nomor Invoice (e.g. PJL-...)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Pelunasan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.PelunasanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/master/resources": {
            "get": {
                "description": "Mengambil daftar Category, Brand, dan Supplier untuk pilihan input produk.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Dropdown Resources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produ2cts": {
            "get": {
                "description": "Mengambil semua data produk dengan pagination dan pencarian nama/kode.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get All Products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by Name or Code",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Create New Product",
                "parameters": [
                    {
                        "description": "Product Body",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get Product by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ProductRequest"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Update Existing Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Data",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Products"
                ],
                "summary": "Delete Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Brand": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.CreateTransactionRequest": {
            "type": "object",
            "properties": {
                "amount_paid": {
                    "type": "number",
                    "example": 2500000
                },
                "customer": {
                    "$ref": "#/definitions/domain.CustomerRequest"
                },
                "invoice": {
                    "type": "string",
                    "example": "PJL-123456"
                },
                "is_dp": {
                    "type": "boolean",
                    "example": false
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SalesItemRequest"
                    }
                },
                "member_name": {
                    "type": "string",
                    "example": "Desak"
                },
                "payment_method": {
                    "type": "string",
                    "example": "Bayar Tunai"
                },
                "user_id": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "domain.Customer": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "identity_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.CustomerRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "identity_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "domain.PelunasanRequest": {
            "type": "object",
            "properties": {
                "amount_paid": {
                    "type": "number",
                    "example": 500000
                },
                "is_dp": {
                    "type": "boolean",
                    "example": false
                },
                "payment_method": {
                    "type": "string",
                    "example": "Bayar Tunai"
                },
                "status": {
                    "type": "string",
                    "example": "Lunas"
                }
            }
        },
        "domain.Product": {
            "type": "object",
            "properties": {
                "brand": {
                    "$ref": "#/definitions/domain.Brand"
                },
                "brandID": {
                    "type": "integer"
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "categoryID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "hbeli": {
                    "type": "number"
                },
                "hjual": {
                    "type": "number"
                },
                "hpokok": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "saldo": {
                    "type": "number"
                },
                "satuan": {
                    "type": "string"
                },
                "supplier": {
                    "$ref": "#/definitions/domain.Supplier"
                },
                "supplierID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.ProductRequest": {
            "type": "object",
            "properties": {
                "brand": {
                    "$ref": "#/definitions/domain.Brand"
                },
                "brandID": {
                    "type": "integer"
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "categoryID": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "hbeli": {
                    "type": "number"
                },
                "hjual": {
                    "type": "number"
                },
                "hpokok": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "saldo": {
                    "type": "number"
                },
                "satuan": {
                    "type": "string"
                },
                "supplier": {
                    "$ref": "#/definitions/domain.Supplier"
                },
                "supplierID": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.ProductResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "$ref": "#/definitions/domain.Brand"
                },
                "brandID": {
                    "type": "integer"
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "categoryID": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "hbeli": {
                    "type": "number"
                },
                "hjual": {
                    "type": "number"
                },
                "hpokok": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "saldo": {
                    "type": "number"
                },
                "satuan": {
                    "type": "string"
                },
                "supplier": {
                    "$ref": "#/definitions/domain.Supplier"
                },
                "supplierID": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.Sales": {
            "type": "object",
            "properties": {
                "amount_paid": {
                    "type": "number"
                },
                "change": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "customer": {
                    "$ref": "#/definitions/domain.Customer"
                },
                "customer_id": {
                    "type": "integer"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "discount": {
                    "description": "Potongan harga",
                    "type": "number"
                },
                "h_beli": {
                    "type": "number"
                },
                "h_jual": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "invoice": {
                    "type": "string"
                },
                "is_dp": {
                    "type": "boolean"
                },
                "member_name": {
                    "description": "Dari field 'Member' di gambar",
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "product": {
                    "$ref": "#/definitions/domain.Product"
                },
                "product_id": {
                    "type": "integer"
                },
                "qty": {
                    "type": "number"
                },
                "shift": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_netto": {
                    "description": "Harga setelah diskon",
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/domain.User"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.SalesItemRequest": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "number",
                    "example": 0
                },
                "price": {
                    "type": "number",
                    "example": 20000
                },
                "product_search": {
                    "type": "string",
                    "example": "POLY 32RG9059"
                },
                "qty": {
                    "type": "number",
                    "example": 1
                }
            }
        },
        "domain.SalesResponse": {
            "type": "object",
            "properties": {
                "amount_paid": {
                    "type": "number"
                },
                "change": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "discount": {
                    "description": "Potongan harga",
                    "type": "number"
                },
                "h_beli": {
                    "type": "number"
                },
                "h_jual": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "invoice": {
                    "type": "string"
                },
                "is_dp": {
                    "type": "boolean"
                },
                "member_name": {
                    "description": "Dari field 'Member' di gambar",
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "product": {
                    "$ref": "#/definitions/domain.ProductResponse"
                },
                "product_id": {
                    "type": "integer"
                },
                "qty": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "total_netto": {
                    "description": "Harga setelah diskon",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.SalesTransactionGroup": {
            "type": "object",
            "properties": {
                "amount_paid": {
                    "type": "number"
                },
                "change": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "customer": {
                    "$ref": "#/definitions/domain.Customer"
                },
                "customer_id": {
                    "type": "integer"
                },
                "invoice": {
                    "type": "string"
                },
                "is_dp": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Sales"
                    }
                },
                "member_name": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "remaining_amount": {
                    "type": "number"
                },
                "shift": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_netto": {
                    "type": "number"
                },
                "total_qty": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/domain.User"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.Supplier": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "description": "admin, kasir, super-kasir, akuntan, superadmin",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Backend Cashier API",
	Description:      "API Sistem Kasir dengan Manajemen Stok dan Biaya Operasional.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
